import js from '@eslint/js';
import prettier from 'eslint-config-prettier/flat';
import nextPlugin from '@next/eslint-plugin-next';
import betterTailwindcss from 'eslint-plugin-better-tailwindcss';
import reactHooks from 'eslint-plugin-react-hooks';
import { defineConfig, globalIgnores } from 'eslint/config';
import { fileURLToPath } from 'node:url';
import tseslint from 'typescript-eslint';

// A color written by hand: hexadecimal, rgb() or rgba().
const handWrittenColor = '/#[0-9A-Fa-f]{3,8}\\b|rgba?\\(/';

// Shared by every workspace: `eslint .` in a package resolves this file from the root.
export default defineConfig(
  globalIgnores([
    '**/dist/',
    '**/coverage/',
    '**/.turbo/',
    // Expo: generated types, and native folders written by prebuild (never versioned).
    '**/.expo/',
    'apps/mobile/ios/',
    'apps/mobile/android/',
    // Next.js: build output and the route types written by `next typegen`.
    'apps/web/.next/',
    'apps/web/next-env.d.ts',
  ]),
  js.configs.recommended,
  tseslint.configs.strict,
  {
    // React Native app: rules of hooks and React Compiler checks. eslint-config-expo is left
    // out: its React and import plugins do not support ESLint 10 yet.
    files: ['apps/mobile/**/*.{ts,tsx}'],
    extends: [reactHooks.configs.flat.recommended],
    rules: {
      'react-hooks/exhaustive-deps': 'error',
    },
  },
  {
    // Styles of the app come from tokens.json only (#125): a class outside the generated preset,
    // an arbitrary value (`text-[15px]`) or a color written by hand fails the lint.
    files: ['apps/mobile/**/*.{ts,tsx}'],
    plugins: { 'better-tailwindcss': betterTailwindcss },
    settings: {
      'better-tailwindcss': {
        tailwindConfig: fileURLToPath(new URL('apps/mobile/tailwind.config.js', import.meta.url)),
        selectors: [
          {
            kind: 'attribute',
            name: '^(?:className|\\w+ClassName)$',
            match: [{ type: 'strings' }],
          },
          // Variant tables of the base components: `{ primary: { className: 'bg-blue' } }`.
          {
            kind: 'variable',
            name: '^variants$',
            match: [{ type: 'objectValues', path: '^.*className$' }],
          },
        ],
      },
    },
    rules: {
      'better-tailwindcss/no-unknown-classes': 'error',
      'better-tailwindcss/no-restricted-classes': [
        'error',
        {
          restrict: [
            { pattern: '\\[.*\\]', message: 'Arbitrary value: use a token of tokens.json.' },
          ],
        },
      ],
      'no-restricted-syntax': [
        'error',
        {
          selector: `Literal[value=${handWrittenColor}]`,
          message: 'Color written by hand: use a color token of @widoo/tokens.',
        },
        {
          selector: `TemplateElement[value.raw=${handWrittenColor}]`,
          message: 'Color written by hand: use a color token of @widoo/tokens.',
        },
      ],
    },
  },
  {
    // Site (Next.js): rules of hooks, and the Next.js rules for pages, links, images and fonts.
    files: ['apps/web/**/*.{ts,tsx}'],
    extends: [reactHooks.configs.flat.recommended],
    plugins: { '@next/next': nextPlugin },
    settings: { next: { rootDir: fileURLToPath(new URL('apps/web/', import.meta.url)) } },
    rules: {
      ...nextPlugin.configs.recommended.rules,
      ...nextPlugin.configs['core-web-vitals'].rules,
      'react-hooks/exhaustive-deps': 'error',
    },
  },
  {
    // Same rule as the app: styles from tokens.json only (Site-Web, apps/web/AGENTS.md).
    files: ['apps/web/src/**/*.{ts,tsx}'],
    plugins: { 'better-tailwindcss': betterTailwindcss },
    settings: {
      'better-tailwindcss': {
        tailwindConfig: fileURLToPath(new URL('apps/web/tailwind.config.cjs', import.meta.url)),
        selectors: [{ kind: 'attribute', name: '^className$', match: [{ type: 'strings' }] }],
      },
    },
    rules: {
      'better-tailwindcss/no-unknown-classes': 'error',
      'better-tailwindcss/no-restricted-classes': [
        'error',
        {
          restrict: [
            { pattern: '\\[.*\\]', message: 'Arbitrary value: use a token of tokens.json.' },
          ],
        },
      ],
      'no-restricted-syntax': [
        'error',
        {
          selector: `Literal[value=${handWrittenColor}]`,
          message: 'Color written by hand: use a color token of @widoo/tokens.',
        },
        {
          selector: `TemplateElement[value.raw=${handWrittenColor}]`,
          message: 'Color written by hand: use a color token of @widoo/tokens.',
        },
      ],
    },
  },
  {
    // CommonJS run by Node: the Tailwind preset generated by @widoo/tokens, and the Babel, Metro
    // and Tailwind configuration of the app.
    files: ['**/*.cjs', 'apps/mobile/*.config.js'],
    languageOptions: {
      sourceType: 'commonjs',
      globals: { module: 'writable', require: 'readonly', __dirname: 'readonly' },
    },
    rules: {
      '@typescript-eslint/no-require-imports': 'off',
    },
  },
  prettier,
);
