/**
 * Single database schema (wiki Modele-de-Donnees). Every change goes through `pnpm db:generate`,
 * which writes a versioned migration under `generated/migrations`: migrations stay additive.
 * Enum values come from the taxonomies of `@widoo/shared`, never from display labels.
 */
import { taxonomies, type Audience, type Condition, type Mood } from '@widoo/shared';
import { sql, type SQL } from 'drizzle-orm';
import {
  boolean,
  check,
  date,
  index,
  integer,
  jsonb,
  numeric,
  pgEnum,
  pgTable,
  smallint,
  text,
  time,
  timestamp,
  unique,
  uuid,
  type AnyPgColumn,
} from 'drizzle-orm/pg-core';
import { geographyBBox, geographyPoint } from './geography';
import { uuidv7 } from './uuid';

export const userRole = pgEnum('user_role', taxonomies.userRoles);
/** Plan of a user, and plan a route requires (`routes.access`). */
export const plan = pgEnum('plan', taxonomies.plans);
export const placeCategory = pgEnum('place_category', taxonomies.placeCategories);
export const priceRange = pgEnum('price_range', taxonomies.priceRanges);
export const verificationStatus = pgEnum('verification_status', taxonomies.verificationStatuses);
export const routeStatus = pgEnum('route_status', taxonomies.routeStatuses);
export const transport = pgEnum('transport', taxonomies.transports);
export const durationBucket = pgEnum('duration_bucket', taxonomies.durations);
export const budgetBucket = pgEnum('budget_bucket', taxonomies.budgets);
export const bookingProvider = pgEnum('booking_provider', taxonomies.bookingProviders);
/** Technical only, never displayed: no label in `shared`. */
export const mediaOwnerType = pgEnum('media_owner_type', ['route', 'place']);

/** UUID v7 primary key, generated by the API (Postgres 16 has no `uuidv7()`). */
const id = () =>
  uuid('id')
    .primaryKey()
    .$defaultFn(() => uuidv7());
const createdAt = () => timestamp('created_at', { withTimezone: true }).notNull().defaultNow();
const updatedAt = () =>
  timestamp('updated_at', { withTimezone: true })
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date());

/**
 * `column <@ ARRAY[...]`: every element of a `text[]` column is a key of the taxonomy. Keys are
 * snake_case constants (tested in `shared`), so inlining them is safe.
 */
function onlyKeysOf(column: AnyPgColumn, keys: readonly string[]): SQL {
  const list = keys.map((key) => `'${key}'`).join(', ');
  return sql`${column} <@ ARRAY[${sql.raw(list)}]::text[]`;
}

export const cities = pgTable('cities', {
  id: id(),
  slug: text('slug').notNull().unique(),
  name: text('name').notNull(),
  center: geographyPoint('center').notNull(),
  bounds: geographyBBox('bounds').notNull(),
  /** IANA name, e.g. `Europe/Paris`: opening hours are local times of the city. */
  timezone: text('timezone').notNull(),
  isActive: boolean('is_active').notNull().default(false),
});

export const users = pgTable('users', {
  id: id(),
  firebaseUid: text('firebase_uid').notNull().unique(),
  /** Null with Sign in with Apple when the user hides the address. */
  email: text('email'),
  firstName: text('first_name'),
  avatarUrl: text('avatar_url'),
  role: userRole('role').notNull().default('user'),
  /** Updated by the RevenueCat webhooks. */
  plan: plan('plan').notNull().default('free'),
  planExpiresAt: timestamp('plan_expires_at', { withTimezone: true }),
  revenuecatAppUserId: text('revenuecat_app_user_id'),
  isPublic: boolean('is_public').notNull().default(true),
  bio: text('bio'),
  /** Weight of the user's place signals. */
  trustScore: numeric('trust_score', { mode: 'number' }).notNull().default(1),
  notificationPrefs: jsonb('notification_prefs').notNull().default({}),
  createdAt: createdAt(),
  /** Soft delete, then purge (wiki Securite-et-RGPD). */
  deletedAt: timestamp('deleted_at', { withTimezone: true }),
});

export const places = pgTable(
  'places',
  {
    id: id(),
    cityId: uuid('city_id')
      .notNull()
      .references(() => cities.id),
    name: text('name').notNull(),
    category: placeCategory('category').notNull(),
    location: geographyPoint('location').notNull(),
    /** Formatted address; street, postcode and arrondissement in `address_components`. */
    address: text('address').notNull(),
    addressComponents: jsonb('address_components'),
    isIndoor: boolean('is_indoor').notNull().default(false),
    priceRange: priceRange('price_range'),
    websiteUrl: text('website_url'),
    phone: text('phone'),
    /** Google Places, OpenStreetMap... identifiers, for later. */
    externalRefs: jsonb('external_refs').notNull().default({}),
    /** No default: whoever creates a place states how far it is verified. */
    verificationStatus: verificationStatus('verification_status').notNull(),
    verifiedAt: timestamp('verified_at', { withTimezone: true }),
    /** Weighted by the trust score of each confirmation. */
    confirmationsSinceVerified: numeric('confirmations_since_verified', { mode: 'number' })
      .notNull()
      .default(0),
    createdBy: uuid('created_by').references(() => users.id, { onDelete: 'set null' }),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    index('places_location_idx').using('gist', t.location),
    index('places_city_category_idx').on(t.cityId, t.category),
    index('places_name_trgm_idx').using('gin', t.name.op('gin_trgm_ops')),
  ],
);

/** No row on a weekday: closed that day. No row at all: hours unknown. */
export const placeHours = pgTable(
  'place_hours',
  {
    id: id(),
    placeId: uuid('place_id')
      .notNull()
      .references(() => places.id, { onDelete: 'cascade' }),
    /** 0 = Monday. */
    weekday: smallint('weekday').notNull(),
    /** Several slots a day for split hours; `closes` before `opens` runs past midnight. */
    opens: time('opens').notNull(),
    closes: time('closes').notNull(),
    /** Seasonal hours; null when always valid. */
    validFrom: date('valid_from'),
    validTo: date('valid_to'),
  },
  (t) => [
    index('place_hours_place_idx').on(t.placeId),
    check('place_hours_weekday_check', sql`${t.weekday} between 0 and 6`),
  ],
);

export const routes = pgTable(
  'routes',
  {
    id: id(),
    cityId: uuid('city_id')
      .notNull()
      .references(() => cities.id),
    /** Null once the author's account is purged. */
    authorId: uuid('author_id').references(() => users.id, { onDelete: 'set null' }),
    /** « Par Widoo ». */
    isOfficial: boolean('is_official').notNull().default(false),
    status: routeStatus('status').notNull().default('draft'),
    access: plan('access').notNull().default('free'),
    sponsored: boolean('sponsored').notNull().default(false),
    /** Private link token. */
    shareToken: text('share_token').unique(),
    title: text('title').notNull(),
    description: text('description'),
    moods: text('moods').array().$type<Mood[]>().notNull().default([]),
    audiences: text('audiences').array().$type<Audience[]>().notNull().default([]),
    /** Entered and derived conditions. */
    conditions: text('conditions').array().$type<Condition[]>().notNull().default([]),
    transport: transport('transport').notNull().default('walk'),
    /** First step; null while the route has none. */
    startLocation: geographyPoint('start_location'),
    /** Envelope of the steps; null while the route has none. */
    bounds: geographyBBox('bounds'),
    /** Orchestration result: duration, budget, distance, walking, effort, warnings, `computed_at`. */
    computed: jsonb('computed'),
    durationBucket: durationBucket('duration_bucket'),
    budgetBucket: budgetBucket('budget_bucket'),
    publishedAt: timestamp('published_at', { withTimezone: true }),
    /** Denormalized counters and rating, recomputed. */
    stats: jsonb('stats').notNull().default({}),
    /** Score components except proximity and context, recomputed nightly. */
    recommendation: jsonb('recommendation'),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    index('routes_bounds_idx').using('gist', t.bounds),
    index('routes_start_location_idx').using('gist', t.startLocation),
    index('routes_city_status_idx').on(t.cityId, t.status),
    index('routes_moods_idx').using('gin', t.moods),
    index('routes_audiences_idx').using('gin', t.audiences),
    index('routes_conditions_idx').using('gin', t.conditions),
    index('routes_duration_bucket_idx').on(t.durationBucket),
    index('routes_budget_bucket_idx').on(t.budgetBucket),
    check('routes_moods_check', onlyKeysOf(t.moods, taxonomies.moods)),
    check('routes_audiences_check', onlyKeysOf(t.audiences, taxonomies.audiences)),
    check('routes_conditions_check', onlyKeysOf(t.conditions, taxonomies.conditions)),
  ],
);

export const steps = pgTable(
  'steps',
  {
    id: id(),
    routeId: uuid('route_id')
      .notNull()
      .references(() => routes.id, { onDelete: 'cascade' }),
    position: smallint('position').notNull(),
    /** A place used by a route cannot be deleted: it is marked `closed` instead. */
    placeId: uuid('place_id')
      .notNull()
      .references(() => places.id),
    /** Null: the place name is shown instead. */
    title: text('title'),
    description: text('description'),
    durationMin: smallint('duration_min').notNull(),
    /** Estimated, in euros. */
    costPerPerson: numeric('cost_per_person', { mode: 'number' }),
    bookingRequired: boolean('booking_required').notNull().default(false),
    bookingUrl: text('booking_url'),
    bookingProvider: bookingProvider('booking_provider'),
    /** « Passer par la rue des Rosiers ». */
    transitionNote: text('transition_note'),
    /** Computed: `distance_m`, `duration_min`, `mode`, `estimated`. */
    transition: jsonb('transition'),
  },
  (t) => [
    unique('steps_route_position_unique').on(t.routeId, t.position),
    index('steps_place_idx').on(t.placeId),
  ],
);

export const media = pgTable(
  'media',
  {
    id: id(),
    ownerType: mediaOwnerType('owner_type').notNull(),
    /** Route or place id, depending on `owner_type`. */
    ownerId: uuid('owner_id').notNull(),
    storagePath: text('storage_path').notNull(),
    width: integer('width').notNull(),
    height: integer('height').notNull(),
    position: smallint('position').notNull().default(0),
    uploadedBy: uuid('uploaded_by').references(() => users.id, { onDelete: 'set null' }),
    createdAt: createdAt(),
  },
  (t) => [index('media_owner_idx').on(t.ownerType, t.ownerId, t.position)],
);

/** Thresholds (buckets, verification, rule limits), read by the API at startup. */
export const settings = pgTable('settings', {
  key: text('key').primaryKey(),
  value: jsonb('value').notNull(),
  updatedAt: updatedAt(),
});
