import type { Taxonomy, TaxonomyValue } from '../taxonomies';

export type TaxonomyLabels = { [T in Taxonomy]: Record<TaxonomyValue<T>, string> };

/** French labels: the compiler rejects a taxonomy value without a label, or a label without a value. */
export const fr = {
  audiences: {
    solo: 'Solo',
    couple: 'Couple',
    family: 'Famille',
    friends: 'Entre amis',
    dog_friendly: 'Dog friendly',
    kids_friendly: 'Kids friendly',
  },
  budgets: { free: 'Gratuit', low: 'Petit budget', medium: 'Moyen', premium: 'Premium' },
  durations: {
    '1_2h': '1 à 2 h',
    half_day: 'Demi-journée',
    full_day: 'Journée',
    weekend: 'Week-end',
  },
  transports: { walk: 'À pied', bike: 'Vélo', metro: 'Métro', car: 'Voiture' },
  moods: {
    culture: 'Culture',
    nature: 'Nature',
    shopping: 'Shopping',
    food: 'Gastronomie',
    romantic: 'Romantique',
    unusual: 'Insolite',
    instagrammable: 'Instagrammable',
    relax: 'Détente',
    sport: 'Sportif',
  },
  conditions: {
    no_booking: 'Sans réservation',
    wheelchair: 'Accessible PMR',
    indoor: 'Intérieur',
    outdoor: 'Extérieur',
    sunny: 'Beau temps',
    rainy: 'Jour de pluie',
  },
  placeCategories: {
    restaurant: 'Restaurant',
    cafe: 'Café',
    bar: 'Bar',
    bakery: 'Boulangerie',
    museum: 'Musée',
    gallery: 'Galerie',
    monument: 'Monument',
    park: 'Parc',
    viewpoint: 'Point de vue',
    shop: 'Boutique',
    activity: 'Activité',
    event_venue: 'Spectacle',
    walk: 'Balade',
    other: 'Autre',
  },
  routeStatuses: {
    draft: 'Brouillon',
    private: 'Privé',
    pending: 'En attente de validation',
    changes_requested: 'Modifications demandées',
    published: 'Publié',
    needs_fix: 'À corriger',
    rejected: 'Refusé',
    unpublished: 'Dépublié',
  },
  priceRanges: { free: 'Gratuit', low: 'Bon marché', medium: 'Prix moyen', high: 'Haut de gamme' },
  verificationStatuses: {
    verified: 'Vérifié',
    stale: 'À vérifier',
    flagged: 'Signalé',
    closed: 'Fermé',
  },
  signalReasons: {
    closed_permanently: 'Fermé définitivement',
    closed_temporarily: 'Fermé temporairement',
    wrong_hours: 'Horaires erronés',
    wrong_address: 'Adresse erronée',
    other: 'Autre',
  },
  userRoles: {
    user: 'Utilisateur',
    editor: 'Éditeur',
    moderator: 'Modérateur',
    admin: 'Administrateur',
  },
  plans: { free: 'Gratuit', premium: 'Premium' },
  bookingProviders: {
    restaurant: 'Restaurant',
    ticketing: 'Billetterie',
    activity: 'Activité',
    other: 'Autre',
  },
} as const satisfies TaxonomyLabels;
